id: /subscriptions/1da52b57-468a-4dc6-ba36-1255cc1f6e8e/resourceGroups/rg-ai-ticket-automation/providers/Microsoft.App/containerapps/ca-bwwjb3m2kgmii
identity:
  type: None
location: Sweden Central
name: ca-bwwjb3m2kgmii
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: ca-bwwjb3m2kgmii.ashycoast-9cdf72ee.swedencentral.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 8000
      traffic:
      - latestRevision: true
        weight: 100
      transport: Http
    maxInactiveRevisions: null
    registries:
    - identity: ''
      passwordSecretRef: crbwwjb3m2kgmiiazurecrio-crbwwjb3m2kgmii
      server: crbwwjb3m2kgmii.azurecr.io
      username: crbwwjb3m2kgmii
    runtime: null
    secrets:
    - name: acr-password
    - name: crbwwjb3m2kgmiiazurecrio-crbwwjb3m2kgmii
    service: null
  customDomainVerificationId: 21935B65D9BDE3E63127245C94B6565F1C6A57E85A86A106B564DBEF9D09CAAB
  delegatedIdentities: []
  environmentId: /subscriptions/1da52b57-468a-4dc6-ba36-1255cc1f6e8e/resourceGroups/rg-ai-ticket-automation/providers/Microsoft.App/managedEnvironments/ca-bwwjb3m2kgmii-env
  eventStreamEndpoint: https://swedencentral.azurecontainerapps.dev/subscriptions/1da52b57-468a-4dc6-ba36-1255cc1f6e8e/resourceGroups/rg-ai-ticket-automation/containerApps/ca-bwwjb3m2kgmii/eventstream
  latestReadyRevisionName: ca-bwwjb3m2kgmii--0000004
  latestRevisionFqdn: ca-bwwjb3m2kgmii--0000004.ashycoast-9cdf72ee.swedencentral.azurecontainerapps.io
  latestRevisionName: ca-bwwjb3m2kgmii--0000004
  managedEnvironmentId: /subscriptions/1da52b57-468a-4dc6-ba36-1255cc1f6e8e/resourceGroups/rg-ai-ticket-automation/providers/Microsoft.App/managedEnvironments/ca-bwwjb3m2kgmii-env
  outboundIpAddresses:
  - 9.223.66.195
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - image: crbwwjb3m2kgmii.azurecr.io/ai-ticket-automation/servicedesk-simulator-ai-ticket-automation:v2
      name: servicedesk-simulator
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 1
      minReplicas: 0
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: null
resourceGroup: rg-ai-ticket-automation
systemData:
  createdAt: '2026-05-19T19:05:16.5799677'
  createdBy: sanjay.singh@microsoft.com
  createdByType: User
  lastModifiedAt: '2026-05-19T21:29:16.5134534'
  lastModifiedBy: sanjay.singh@microsoft.com
  lastModifiedByType: User
tags:
  SecurityControl: Ignore
  azd-env-name: ai-ticket-automation
  azd-service-name: servicedesk-simulator
type: Microsoft.App/containerApps
